name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Linter
      run: |
        swiftlint lint --reporter github-actions-logging
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
